"""Compatibility facade for card services split by responsibility."""

from app.services.card_common import (
    DuplicateInventoryItemError,
    normalize_name,
    _parse_language_preferences,
    _normalize_language_code,
    _extract_set_code_language_prefix,
    _validate_set_code_language,
    _normalize_optional_text,
    _normalize_tags,
    _dedupe_text_values,
    _card_set_lookup_codes,
    _find_matching_card_set,
    _load_cardmarket_set_slug_hints,
    _build_failed_cardmarket_resolution,
    _update_card_set_cardmarket_metadata,
    _normalize_price_value,
    _first_image,
    _placeholder_url,
    _proxy_remote_image_url,
    _cardmarket_url,
    _preferred_cardmarket_locale,
    _remote_image_url,
    _derive_card_number,
    _derive_print_language,
    _resolve_default_remote_price,
    _build_print_label,
    _normalize_lookup_value,
    _card_numbers_match,
    _set_code_language_neutral_signature,
    _set_codes_match_language_neutral,
    _cardmarket_variant_number,
    _manual_cardmarket_resolution,
    _append_local_cardmarket_reference,
    _is_verified_cardmarket_quality,
    _is_safe_cardmarket_quality,
    _price_note,
    _is_exact_inventory_duplicate_candidate,
    _find_exact_inventory_duplicate,
)

from app.services.card_lookup import (
    _load_local_cardmarket_references,
    _find_local_cardmarket_references,
    search_card_catalog,
    _fetch_remote_card_for_languages,
    _resolve_english_cardmarket_naming,
    _load_ygoprodeck_external_id,
    _matches_cardmarket_remote_print,
    _cardmarket_variant_count_for_remote_card,
    _resolve_exact_cardmarket_product,
    get_card_lookup,
)

from app.services.card_read import (
    _latest_price_entry,
    _group_source_mappings,
    _mappings_for_item,
    _load_source_mappings,
    _load_active_price_jobs,
    _load_exact_cardmarket_references,
    _resolve_cardmarket_link,
    _build_pricing_status,
    _display_price_value,
    _display_optional_price_value,
    _display_price_sample_values,
    _serialize_price_history_point,
    serialize_card_summary,
    list_cards,
    get_card_detail,
    get_filter_options,
    price_history_for_card,
)

from app.services.card_write import (
    upsert_card,
    delete_card,
    update_cardmarket_link,
)

__all__ = [
    "DuplicateInventoryItemError",
    "normalize_name",
    "search_card_catalog",
    "get_card_lookup",
    "serialize_card_summary",
    "list_cards",
    "get_card_detail",
    "upsert_card",
    "delete_card",
    "update_cardmarket_link",
    "get_filter_options",
    "price_history_for_card",
]
