"""Compatibility facade for sync job orchestration and task implementations."""

from app.services.sync_jobs import (
    _normalize_target_ids,
    _extract_price_targets,
    _price_targets_overlap,
    _build_job_lock_key,
    _merge_price_job_payload,
    _job_health,
    _format_job_log_value,
    _trim_job_excerpt,
    _render_job_log_entry,
    _append_job_log_blob,
    _apply_job_log_update,
    _append_job_log,
    _build_price_item_context,
    _build_snapshot_log_context,
    _build_completion_excerpt,
    serialize_sync_job,
    create_sync_job_record,
    queue_sync_job,
    queue_price_update_job,
    get_sync_job,
    list_sync_jobs,
    retry_sync_job,
    get_provider_statuses,
    fail_stale_running_jobs,
    claim_next_sync_job,
    _claim_job_by_id,
    _complete_job,
    _fail_job,
    _job_handlers,
    process_claimed_sync_job,
    execute_sync_job,
)

from app.services.sync_tasks import (
    bootstrap_missing_media,
    _persist_job_progress,
    _find_mapping,
    _run_card_data_sync,
    _load_price_sync_items,
    _apply_cardmarket_snapshot_metadata,
    _persist_price_snapshot,
    _price_provider_rate_limit,
    _record_price_item_failure,
    _run_price_sync,
    _run_image_sync,
    _price_change,
    _run_trend_rebuild,
)

__all__ = [
    "serialize_sync_job",
    "create_sync_job_record",
    "queue_sync_job",
    "queue_price_update_job",
    "get_sync_job",
    "list_sync_jobs",
    "retry_sync_job",
    "get_provider_statuses",
    "bootstrap_missing_media",
    "fail_stale_running_jobs",
    "claim_next_sync_job",
    "process_claimed_sync_job",
    "execute_sync_job",
]
