from .product_resolver import CardmarketProductResolver, get_cardmarket_product_resolver
from .product_url_builder import CardmarketProductUrlBuilder
from .set_slug_resolver import CardmarketSetSlugCandidate, CardmarketSetSlugResolver, get_cardmarket_set_slug_resolver
from .types import CardmarketPrintContext, CardmarketResolvedProduct
from .url_builder import (
    CARDMARKET_BASE_URL,
    CARDMARKET_CATEGORY,
    CARDMARKET_MATCH_AMBIGUOUS,
    CARDMARKET_MATCH_EXACT,
    CARDMARKET_MATCH_EXACT_VARIANT,
    CARDMARKET_MATCH_FAILED,
    CARDMARKET_MATCH_MANUAL,
    CARDMARKET_SAFE_MATCH_QUALITIES,
    CARDMARKET_MATCH_SET_NAME,
    CardmarketLinkResolution,
    CardmarketUrlBuilder,
    CardmarketUrlCandidate,
    build_cardmarket_fallback_url,
    build_cardmarket_product_slug,
    build_cardmarket_product_url,
    build_cardmarket_set_slug,
    normalize_cardmarket_product_url,
    resolve_cardmarket_product_url,
    slugify_cardmarket_segment,
    split_cardmarket_product_url,
)

__all__ = [
    "CARDMARKET_BASE_URL",
    "CARDMARKET_CATEGORY",
    "CARDMARKET_MATCH_AMBIGUOUS",
    "CARDMARKET_MATCH_EXACT",
    "CARDMARKET_MATCH_EXACT_VARIANT",
    "CARDMARKET_MATCH_FAILED",
    "CARDMARKET_MATCH_MANUAL",
    "CARDMARKET_SAFE_MATCH_QUALITIES",
    "CARDMARKET_MATCH_SET_NAME",
    "CardmarketLinkResolution",
    "CardmarketPrintContext",
    "CardmarketProductUrlBuilder",
    "CardmarketProductResolver",
    "CardmarketResolvedProduct",
    "CardmarketSetSlugCandidate",
    "CardmarketSetSlugResolver",
    "CardmarketUrlBuilder",
    "CardmarketUrlCandidate",
    "build_cardmarket_fallback_url",
    "build_cardmarket_product_slug",
    "build_cardmarket_product_url",
    "build_cardmarket_set_slug",
    "get_cardmarket_product_resolver",
    "get_cardmarket_set_slug_resolver",
    "normalize_cardmarket_product_url",
    "resolve_cardmarket_product_url",
    "slugify_cardmarket_segment",
    "split_cardmarket_product_url",
]
